### PR TITLE
Database planning

### PR DESCRIPTION
**Pull request by luis-novoa**
Finished planning the database structure. Please review it and give us a feedback.

### CODE REVIEW

**Review by davidauza-engineer — APPROVED** [review]
Everything is ready for the TSE review. Thank you @luis-novoa.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

NIce introduction to the project. However, to move forward, there are some requirements to take in consideration

1. As indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/imglink.png),  the User table has `image_link` column, which is missing in yours

2. You need a `ID` field into the `Like` table

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by davidauza-engineer** [comment]
Hi @maelfosso 

Thank you very much, we'll implement the changes ASAP and ask for another code review 😃

**Review by davidauza-engineer — APPROVED** [review]
All the required changes were successfully implemented 👍

**Review by maelfosso — APPROVED** [review]
# Congratulations :red_circle: :clap: 

You can move forward :+1: 
Good luck with the next milestone :handshake: 

Mael FOSSO

**Comment by davidauza-engineer** [comment]
Thank you very much @maelfosso and @luis-novoa !

**Pull request merged**
