### PR TITLE
2 rows Friendship Implementation

### PR DESCRIPTION
**Pull request by luis-novoa**
Dear TSE and David,

Our work seems to be done. Please, check for errors and points of improvement.

Changes made include:

- Refactor of the Friendship model to include 2 rows when a Friendship is accepted.

- Corresponding unit and integration tests.

- Remove unnecessary code after refactoring.

Best regards,
Luis Novoa

### CODE REVIEW

**Review by davidauza-engineer — APPROVED** [review]
Everything is ready for a TSE review. Thank you very much @luis-novoa

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello, Thank you for the job done!
However, there are some requirements that need to be met

1. It was asked to create an additional row with reversed user-friend pair, **when the friendship is confirm**. But as I noticed, you created the row when a user ask for a friendship to another one.
```ruby
  Friendship Load (0.7ms)  SELECT  "friendships".* FROM "friendships" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Friendship id: 1, user_id: 2, friend_id: 1, confirmed: false, created_at: "2020-03-11 00:06:20", updated_at: "2020-03-11 00:06:20">, #<Friendship id: 2, user_id: 1, friend_id: 2, confirmed: false, created_at: "2020-03-11 00:06:20", updated_at: "2020-03-11 00:06:20">]> 
2.7.0 :002 > 
```

3. The `timeline_posts` method seems not working. Because, with the Friendships state as the one up (result from SQL request) User 1 get all the posts from User 2 whereas there are not friends yet. You can confirm it from these screenshots
Screenshot from 2020-03-10 20-15-10
Screenshot from 2020-03-10 20-14-54

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Review by davidauza-engineer — APPROVED** [review]
Everything was implemented as requested. Thank you @luis-novoa and @maelfosso

**Review by Torres-ssf — APPROVED** [review]
### Project Approved :tada: 
Hi there team :hand: 
I want to congratulate you both for the work on this project :clap: :tada:. It's looking nice and you implemented all requested changes.

### **I'm approving this project**

However, there is something that I need to point out and can make this repo even better. Please check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) to learn more about how you can make your repo looks more professional. It's best practice to summarize all changes made in the PR description. Please edit the PR description before merging to development :smiley: 
Screenshot from 2020-03-11 21-42-08


Good luck with the next milestone.
**Happy coding :computer: **

**Sergio Torres**

**Review by davidauza-engineer — APPROVED** [review]
Thanks a lot, @Torres-ssf, we followed your recommendation and updated PR description and name. Proceeding to merge.

**Pull request merged**
